package com.terrence.crm.dol.utils;

public class ConfigTerrence {
	public static final String MODEL_DESIGNASSIST = "技术支持";
	public static final String MODEL_PRODUCTMANAGE = "生产管理";
	public static final String MODEL_PROCESSTASK = "流程任务";
	public static final String MODEL_PROCESSDEFINE = "流程定义";
	public static final String MODEL_ITEMAPPLY = "物料申请";
	public static final String MODEL_ARBORESCENCE = "物料树状列表";
	public static final String MODEL_ITEM = "物料添加";
	public static final String MODEL_ITEMCODE = "物料代码编辑";
	public static final String MODEL_PROJECTINFO = "项目信息";
	public static final String MODEL_STRUCTURE = "结构型式";
	public static final String MODEL_PROITEM = "项目物料";
	public static final String MODEL_PROJECTFILE = "项目文件";
	public static final String MODEL_SYSORDER = "系统订单";
	public static final String MODEL_USER_MANAGE= "用户管理";
	public static final String MODEL_DEPARTMENT_MANAGE= "部门管理";
	public static final String MODEL_ROLE_MANAGE= "角色管理";
	public static final String MODEL_MENU_MANAGE= "菜单管理";
	public static final String MODEL_CONTRACTCHANGE= "合同变更单";
	public static final String MODEL_CONTRACTREVIEW= "合同评审单";
	public static final String MODEL_PLANTASK= "采购任务";
	public static final String MODEL_PURCHASEPLAN= "采购计划";
	public static final String MODEL_PURCHASEAPPLY= "采购申请单";
	public static final String MODEL_PURCHASEORDER= "采购订单";
	public static final String MODEL_STOREROOMTASK= "库房任务";
	public static final String MODEL_CALLSLIP= "投料单";
	public static final String MODEL_GODOWN= "入库单";
	public static final String MODEL_STOCKBILL= "出库单";
	public static final String MODEL_SALESOUTBOUND= "销售出库单";
	public static final String MODEL_FINANCE_AGENT= "财务经销商比例设置";
	public static final String MODEL_SALESMAN= "财务业务员比例设置";
	public static final String OPT_ADD = "添加";
	public static final String OPT_EDIT = "修改";
	public static final String OPT_DEL = "删除";
	public static final String OPT_COPY = "复制";
	public static final String OPT_PUSH = "下推";
	public static final String OPT_EXAMINE = "审核";
	public static final String OPT_SUBMIT = "提交";
	public static final String OPT_COUNT = "结算";
	public static final String OPT_EXPORT = "导出";
	public static final String OPT_UPLOAD = "上传";
	public static final String OPT_DISPATCH = "分配";
	public static final String OPT_UNEXAMINE = "反审";
	public static final String OPT_AUTOHERITY = "授权";
}